[project]
name = "simplecnn"
version = "0.1.0"
description = """
A lightweight project that implements a simple convolutional neural network (CNN) for image classification tasks using PyTorch.
The focus is on learning basic deep learning concepts, training and evaluating CNN models, and applying them to datasets like CIFAR-10.
"""
dependencies = [
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "matplotlib>=3.10.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[project.scripts]
main = "simplecnn:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/simplecnn"]
